# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  imageRepo: shashank08/pydocproject1
  tag: latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub connection'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
          
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/manifest'
        artifact: 'manifests'
        publishLocation: 'pipeline'
        
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    hubSecret: registryauth
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          targetPath: '$(Pipeline.Workspace)/manifest'
      - task: KubernetesManifest@0
        inputs:
          action: 'createSecret'
          kubernetesServiceConnection: 'Kubernetes Connection'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: '$(hubSecret)'
          dockerRegistryEndpoint: 'Docker Hub connection'
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'Kubernetes Connection'
          namespace: 'default'
          manifests: |
            $(Pipeline.Workspace)/manifest/deployment.yaml
            $(Pipeline.Workspace)/manifest/service.yaml
